variables:
  CUSTOM_TEMPLATE: "true"

image: mcr.microsoft.com/dotnet/core/sdk:3.0

test_image:
  stage: test
  script:
    - color_print INFORMATION "Skip stage"
  except:
    - tags
  dependencies:
    - build_project

include:
  - project: 'smon.monq.ru/devops/devops-files'
    ref: master
    file: "/gitlab-ci-yaml/src/.NET Core Library/gitlab-ci-body.yaml"
  - project: 'smon.monq.ru/devops/devops-files'
    ref: master
    file: "/gitlab-ci-yaml/src/.NET Core Library/gitlab-ci-scripts.yaml"